language: node_js
node_js: "12"
cache:
  yarn: true

before_install:
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git"
  - yarn config set registry //registry.npmjs.org/:_authToken=${NPM_TOKEN}

install:
  - yarn

addons:
  sonarcloud:
    organization: ciklum-digital
    token:
      secure: $SONAR_TOKEN

script:
  - yarn run build
  - yarn run lint
  - yarn run sonar
  - yarn run test:ci

before_deploy:
  - git checkout ${TRAVIS_BRANCH}

deploy:
  provider: script
  script: yarn run publish
  skip_cleanup: true
  on:
    branch: master
